# Generated by Django 4.2.5 on 2023-09-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
